server:
  jetty:
    threads:
      acceptors: 4
      selectors: 8
      min: 8
      max: 200
  port: 8092
  servlet:
    context-path: /hospital-api

spring:
  datasource:
    driver-class-name: org.apache.phoenix.queryserver.client.Driver
    url: jdbc:phoenix:thin:url=http://47.102.100.232:8765;serialization=PROTOBUF
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      test-on-borrow: true
      test-while-idle: true
      max-active: 8
      min-idle: 4
      validation-query: SELECT 1

  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB

  redis:
    database: 22
    host:  fddh-external-1.redis.rds.aliyuncs.com
    port: 6638
    password: Jsyl!!!000
    jedis:
      pool:
        max-active: 1000
        max-wait: -1ms
        max-idle: 16
        min-idle: 8

  quartz:
    job-store-type: memory

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.example.hospital.api.db.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

logging:
  level:
    root: info
    com.example.hospital.api.db.dao: warn
  pattern:
    console: "%d{yyyy/MM/dd HH:mm:ss}  %-5level  %msg%n"

sa-token:
  token-name: token
  timeout: 2592000
  activity-timeout: -1
  allow-concurrent-login: true
  is-share: false
  token-style: uuid
  isReadCookie: false


wechat:
  app-id: wx2231e13ca0648f6b
  app-secret: 5a03ae4a1df6d0d2046d8ece2259d39b
  pay:
    v3:
      patient-wx-api:
        app-id: wx4cb8e9621950da45
        app-secret: 86c4ecfa6be49444ab9b2e9c1490b5aa
        app-v3-secret: 6c6085b7a939450d833d8bb3081d4628
        mch-id: 1526972031
        domain: http://192.168.1.2:9001/patient-wx-api
        cert-path: apiclient_cert.p12

tencent:
  cloud:
    appId: 你的腾讯云APPID
    secretId: 你的腾讯云secretId
    secretKey: 你的腾讯云secretKey
    face:
      groupName: hospital
      region: ap-beijing
  trtc:
    appId: 111
    secretKey: 111
    expire: 86400

minio:
  endpoint: http://localhost:9000
  access-key: root
  secret-key: abc123456

